export const DEPLOY_URL = `https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fsteven-tey%2Fprecedent&project-name=precedent&repository-name=precedent&demo-title=Precedent&demo-description=An%20opinionated%20collection%20of%20components%2C%20hooks%2C%20and%20utilities%20for%20your%20Next%20project.&demo-url=https%3A%2F%2Fprecedent.dev&demo-image=https%3A%2F%2Fprecedent.dev%2Fopengraph-image&env=GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,NEXTAUTH_SECRET&envDescription=How%20to%20get%20these%20env%20variables%3A&envLink=https%3A%2F%2Fgithub.com%2Fsteven-tey%2Fprecedent%2Fblob%2Fmain%2F.env.example&stores=%5B%7B"type"%3A"postgres"%7D%5D`;

export const SHARIA_OPTIONS = [
  { value: 1, label: "تهران", subLabel: "ایران", countryL: "iran" },
  { value: 13, label: "مشهد", subLabel: "ایران", countryL: "iran" },
  { value: 6, label: "تبریز", subLabel: "ایران", countryL: "iran" },
  { value: 11, label: "قم", subLabel: "ایران", countryL: "iran" },
  { value: 2, label: "اصفهان", subLabel: "ایران", countryL: "iran" },
  { value: 8, label: "شیراز", subLabel: "ایران", countryL: "iran" },
  { value: 14, label: "یزد", subLabel: "ایران", countryL: "iran" },
  { value: 3, label: "ارومیه", subLabel: "ایران", countryL: "iran" },
  { value: 19, label: "کرمان", subLabel: "ایران", countryL: "iran" },
  { value: 5, label: "اهواز", subLabel: "ایران", countryL: "iran" },
  { value: 15, label: "بجنورد", subLabel: "ایران", countryL: "iran" },
  { value: 18, label: "گرگان", subLabel: "ایران", countryL: "iran" },
  { value: 17, label: "ساری", subLabel: "ایران", countryL: "iran" },
  { value: 16, label: "رشت", subLabel: "ایران", countryL: "iran" },
  { value: 26, label: "اردبیل", subLabel: "ایران", countryL: "iran" },
  { value: 27, label: "سمنان", subLabel: "ایران", countryL: "iran" },
  { value: 10, label: "قزوین", subLabel: "ایران", countryL: "iran" },
  { value: 25, label: "زنجان", subLabel: "ایران", countryL: "iran" },
  { value: 22, label: "سنندج", subLabel: "ایران", countryL: "iran" },
  { value: 21, label: "کرمانشاه", subLabel: "ایران", countryL: "iran" },
  { value: 24, label: "همدان", subLabel: "ایران", countryL: "iran" },
  { value: 827, label: "بیرجند", subLabel: "ایران", countryL: "iran" },
  { value: 29, label: "ایلام", subLabel: "ایران", countryL: "iran" },
  { value: 30, label: "خرم آباد", subLabel: "ایران", countryL: "iran" },
  { value: 31, label: "شهرکرد", subLabel: "ایران", countryL: "iran" },
  { value: 32, label: "یاسوج", subLabel: "ایران", countryL: "iran" },
  { value: 20, label: "بوشهر", subLabel: "ایران", countryL: "iran" },
  { value: 12, label: "زاهدان", subLabel: "ایران", countryL: "iran" },
  { value: 7, label: "بندرعباس", subLabel: "ایران", countryL: "iran" },
  { value: 4, label: "اراک", subLabel: "ایران", countryL: "iran" },
  { value: 9, label: "کرج", subLabel: "ایران", countryL: "iran" },
  { value: 342, label: "دزفول", subLabel: "ایران", countryL: "iran" },
  { value: 115, label: "کوالالامپور", subLabel: "ایران", countryL: "iran" },
  { value: 991, label: "ساوه", subLabel: "ایران", countryL: "iran" },
  { value: 578, label: "شاهرود", subLabel: "ایران", countryL: "iran" },
  { value: 479, label: "بروجرد", subLabel: "ایران", countryL: "iran" },
  { value: 450, label: "مرند", subLabel: "ایران", countryL: "iran" },
  { value: 822, label: "سبزوار", subLabel: "ایران", countryL: "iran" },
  { value: 976, label: "استانبول", subLabel: "ترکیه", countryL: "iran" },
  { value: 968, label: "کیش", subLabel: "ایران", countryL: "iran" },
];

export const WORLD_CLOCK_TIMEZONES = [
  { label: "Abidjan", value: "Africa/Abidjan" },
  { label: "Algiers", value: "Africa/Algiers" },
  { label: "Bissau", value: "Africa/Bissau" },
  { label: "Cairo", value: "Africa/Cairo" },
  { label: "Casablanca", value: "Africa/Casablanca" },
  { label: "Ceuta", value: "Africa/Ceuta" },
  { label: "El Aaiun", value: "Africa/El_Aaiun" },
  { label: "Johannesburg", value: "Africa/Johannesburg" },
  { label: "Juba", value: "Africa/Juba" },
  { label: "Khartoum", value: "Africa/Khartoum" },
  { label: "Lagos", value: "Africa/Lagos" },
  { label: "Maputo", value: "Africa/Maputo" },
  { label: "Monrovia", value: "Africa/Monrovia" },
  { label: "Nairobi", value: "Africa/Nairobi" },
  { label: "Ndjamena", value: "Africa/Ndjamena" },
  { label: "Sao Tome", value: "Africa/Sao_Tome" },
  { label: "Tripoli", value: "Africa/Tripoli" },
  { label: "Tunis", value: "Africa/Tunis" },
  { label: "Windhoek", value: "Africa/Windhoek" },
  { label: "Adak", value: "America/Adak" },
  { label: "Anchorage", value: "America/Anchorage" },
  { label: "Araguaina", value: "America/Araguaina" },
  { label: "Buenos Aires", value: "America/Argentina/Buenos_Aires" },
  { label: "Catamarca", value: "America/Argentina/Catamarca" },
  { label: "Cordoba", value: "America/Argentina/Cordoba" },
  { label: "Jujuy", value: "America/Argentina/Jujuy" },
  { label: "La Rioja", value: "America/Argentina/La_Rioja" },
  { label: "Mendoza", value: "America/Argentina/Mendoza" },
  { label: "Rio Gallegos", value: "America/Argentina/Rio_Gallegos" },
  { label: "Salta", value: "America/Argentina/Salta" },
  { label: "San Juan", value: "America/Argentina/San_Juan" },
  { label: "San Luis", value: "America/Argentina/San_Luis" },
  { label: "Tucuman", value: "America/Argentina/Tucuman" },
  { label: "Ushuaia", value: "America/Argentina/Ushuaia" },
  { label: "Asuncion", value: "America/Asuncion" },
  { label: "Bahia", value: "America/Bahia" },
  { label: "Bahia Banderas", value: "America/Bahia_Banderas" },
  { label: "Barbados", value: "America/Barbados" },
  { label: "Belem", value: "America/Belem" },
  { label: "Belize", value: "America/Belize" },
  { label: "Boa Vista", value: "America/Boa_Vista" },
  { label: "Bogota", value: "America/Bogota" },
  { label: "Boise", value: "America/Boise" },
  { label: "Cambridge Bay", value: "America/Cambridge_Bay" },
  { label: "Campo Grande", value: "America/Campo_Grande" },
  { label: "Cancun", value: "America/Cancun" },
  { label: "Caracas", value: "America/Caracas" },
  { label: "Cayenne", value: "America/Cayenne" },
  { label: "Chicago", value: "America/Chicago" },
  { label: "Chihuahua", value: "America/Chihuahua" },
  { label: "Ciudad Juarez", value: "America/Ciudad_Juarez" },
  { label: "Costa Rica", value: "America/Costa_Rica" },
  { label: "Cuiaba", value: "America/Cuiaba" },
  { label: "Danmarkshavn", value: "America/Danmarkshavn" },
  { label: "Dawson", value: "America/Dawson" },
  { label: "Dawson Creek", value: "America/Dawson_Creek" },
  { label: "Denver", value: "America/Denver" },
  { label: "Detroit", value: "America/Detroit" },
  { label: "Edmonton", value: "America/Edmonton" },
  { label: "Eirunepe", value: "America/Eirunepe" },
  { label: "El Salvador", value: "America/El_Salvador" },
  { label: "Fort Nelson", value: "America/Fort_Nelson" },
  { label: "Fortaleza", value: "America/Fortaleza" },
  { label: "Glace Bay", value: "America/Glace_Bay" },
  { label: "Goose Bay", value: "America/Goose_Bay" },
  { label: "Grand Turk", value: "America/Grand_Turk" },
  { label: "Guatemala", value: "America/Guatemala" },
  { label: "Guayaquil", value: "America/Guayaquil" },
  { label: "Guyana", value: "America/Guyana" },
  { label: "Halifax", value: "America/Halifax" },
  { label: "Havana", value: "America/Havana" },
  { label: "Hermosillo", value: "America/Hermosillo" },
  { label: "Indianapolis", value: "America/Indianapolis" },
  { label: "Kralendijk", value: "America/Kralendijk" },
  { label: "La Paz", value: "America/La_Paz" },
  { label: "Lima", value: "America/Lima" },
  { label: "Los Angeles", value: "America/Los_Angeles" },
  { label: "Louisville", value: "America/Louisville" },
  { label: "Lower Princes", value: "America/Lower_Princes" },
  { label: "Maceio", value: "America/Maceio" },
  { label: "Managua", value: "America/Managua" },
  { label: "Manaus", value: "America/Manaus" },
  { label: "Marigot", value: "America/Marigot" },
  { label: "Martinique", value: "America/Martinique" },
  { label: "Matamoros", value: "America/Matamoros" },
  { label: "Mazatlan", value: "America/Mazatlan" },
  { label: "Mendoza", value: "America/Mendoza" },
  { label: "Menominee", value: "America/Menominee" },
  { label: "Merida", value: "America/Merida" },
  { label: "Metlakatla", value: "America/Metlakatla" },
  { label: "Mexico City", value: "America/Mexico_City" },
  { label: "Moncton", value: "America/Moncton" },
  { label: "Monterrey", value: "America/Monterrey" },
  { label: "Montevideo", value: "America/Montevideo" },
  { label: "Nassau", value: "America/Nassau" },
  { label: "New York", value: "America/New_York" },
  { label: "Nipigon", value: "America/Nipigon" },
  { label: "Nome", value: "America/Nome" },
  { label: "Noronha", value: "America/Noronha" },
  { label: "North Dakota", value: "America/North_Dakota/Beulah" },
  { label: "Nuuk", value: "America/Nuuk" },
  { label: "Ojinaga", value: "America/Ojinaga" },
  { label: "Panama", value: "America/Panama" },
  { label: "Pangnirtung", value: "America/Pangnirtung" },
  { label: "Paramaribo", value: "America/Paramaribo" },
  { label: "Phoenix", value: "America/Phoenix" },
  { label: "Port-au-Prince", value: "America/Port-au-Prince" },
  { label: "Port of Spain", value: "America/Port_of_Spain" },
  { label: "Porto Velho", value: "America/Porto_Velho" },
  { label: "Puerto Rico", value: "America/Puerto_Rico" },
  { label: "Punta Arenas", value: "America/Punta_Arenas" },
  { label: "Rainy River", value: "America/Rainy_River" },
  { label: "Rankin Inlet", value: "America/Rankin_Inlet" },
  { label: "Recife", value: "America/Recife" },
  { label: "Regina", value: "America/Regina" },
  { label: "Resolute", value: "America/Resolute" },
  { label: "Rio Branco", value: "America/Rio_Branco" },
  { label: "Santarem", value: "America/Santarem" },
  { label: "Santiago", value: "America/Santiago" },
  { label: "Santo Domingo", value: "America/Santo_Domingo" },
  { label: "Sao Paulo", value: "America/Sao_Paulo" },
  { label: "Scoresbysund", value: "America/Scoresbysund" },
  { label: "Sitka", value: "America/Sitka" },
  { label: "St Barthelemy", value: "America/St_Barthelemy" },
  { label: "St Johns", value: "America/St_Johns" },
  { label: "St Kitts", value: "America/St_Kitts" },
  { label: "St Lucia", value: "America/St_Lucia" },
  { label: "St Thomas", value: "America/St_Thomas" },
  { label: "St Vincent", value: "America/St_Vincent" },
  { label: "Swift Current", value: "America/Swift_Current" },
  { label: "Tegucigalpa", value: "America/Tegucigalpa" },
  { label: "Thule", value: "America/Thule" },
  { label: "Thunder Bay", value: "America/Thunder_Bay" },
  { label: "Tijuana", value: "America/Tijuana" },
  { label: "Toronto", value: "America/Toronto" },
  { label: "Tortola", value: "America/Tortola" },
  { label: "Vancouver", value: "America/Vancouver" },
  { label: "Whitehorse", value: "America/Whitehorse" },
  { label: "Winnipeg", value: "America/Winnipeg" },
  { label: "Yakutat", value: "America/Yakutat" },
  { label: "Yellowknife", value: "America/Yellowknife" },
  { label: "Casey", value: "Antarctica/Casey" },
  { label: "Davis", value: "Antarctica/Davis" },
  { label: "DumontDUrville", value: "Antarctica/DumontDUrville" },
  { label: "Macquarie", value: "Antarctica/Macquarie" },
  { label: "Mawson", value: "Antarctica/Mawson" },
  { label: "McMurdo", value: "Antarctica/McMurdo" },
  { label: "Palmer", value: "Antarctica/Palmer" },
  { label: "Rothera", value: "Antarctica/Rothera" },
  { label: "Syowa", value: "Antarctica/Syowa" },
  { label: "Troll", value: "Antarctica/Troll" },
  { label: "Vostok", value: "Antarctica/Vostok" },
  { label: "Longyearbyen", value: "Arctic/Longyearbyen" },
  { label: "Aden", value: "Asia/Aden" },
  { label: "Almaty", value: "Asia/Almaty" },
  { label: "Amman", value: "Asia/Amman" },
  { label: "Anadyr", value: "Asia/Anadyr" },
  { label: "Aqtau", value: "Asia/Aqtau" },
  { label: "Aqtobe", value: "Asia/Aqtobe" },
  { label: "Ashgabat", value: "Asia/Ashgabat" },
  { label: "Atyrau", value: "Asia/Atyrau" },
  { label: "Baghdad", value: "Asia/Baghdad" },
  { label: "Baku", value: "Asia/Baku" },
  { label: "Bangkok", value: "Asia/Bangkok" },
  { label: "Barnaul", value: "Asia/Barnaul" },
  { label: "Beirut", value: "Asia/Beirut" },
  { label: "Bishkek", value: "Asia/Bishkek" },
  { label: "Brunei", value: "Asia/Brunei" },
  { label: "Chita", value: "Asia/Chita" },
  { label: "Choibalsan", value: "Asia/Choibalsan" },
  { label: "Colombo", value: "Asia/Colombo" },
  { label: "Damascus", value: "Asia/Damascus" },
  { label: "Dhaka", value: "Asia/Dhaka" },
  { label: "Dili", value: "Asia/Dili" },
  { label: "Dubai", value: "Asia/Dubai" },
  { label: "Dushanbe", value: "Asia/Dushanbe" },
  { label: "Famagusta", value: "Asia/Famagusta" },
  { label: "Gaza", value: "Asia/Gaza" },
  { label: "Hebron", value: "Asia/Hebron" },
  { label: "Ho Chi Minh", value: "Asia/Ho_Chi_Minh" },
  { label: "Hong Kong", value: "Asia/Hong_Kong" },
  { label: "Hovd", value: "Asia/Hovd" },
  { label: "Irkutsk", value: "Asia/Irkutsk" },
  { label: "Jakarta", value: "Asia/Jakarta" },
  { label: "Jayapura", value: "Asia/Jayapura" },
  { label: "Jerusalem", value: "Asia/Jerusalem" },
  { label: "Kabul", value: "Asia/Kabul" },
  { label: "Kamchatka", value: "Asia/Kamchatka" },
  { label: "Karachi", value: "Asia/Karachi" },
  { label: "Kathmandu", value: "Asia/Kathmandu" },
  { label: "Khandyga", value: "Asia/Khandyga" },
  { label: "Kolkata", value: "Asia/Kolkata" },
  { label: "Krasnoyarsk", value: "Asia/Krasnoyarsk" },
  { label: "Kuala Lumpur", value: "Asia/Kuala_Lumpur" },
  { label: "Kuching", value: "Asia/Kuching" },
  { label: "Kuwait", value: "Asia/Kuwait" },
  { label: "Macau", value: "Asia/Macau" },
  { label: "Magadan", value: "Asia/Magadan" },
  { label: "Makassar", value: "Asia/Makassar" },
  { label: "Manila", value: "Asia/Manila" },
  { label: "Muscat", value: "Asia/Muscat" },
  { label: "Nicosia", value: "Asia/Nicosia" },
  { label: "Novokuznetsk", value: "Asia/Novokuznetsk" },
  { label: "Novosibirsk", value: "Asia/Novosibirsk" },
  { label: "Omsk", value: "Asia/Omsk" },
  { label: "Oral", value: "Asia/Oral" },
  { label: "Phnom Penh", value: "Asia/Phnom_Penh" },
  { label: "Pontianak", value: "Asia/Pontianak" },
  { label: "Pyongyang", value: "Asia/Pyongyang" },
  { label: "Qatar", value: "Asia/Qatar" },
  { label: "Qostanay", value: "Asia/Qostanay" },
  { label: "Qyzylorda", value: "Asia/Qyzylorda" },
  { label: "Riyadh", value: "Asia/Riyadh" },
  { label: "Sakhalin", value: "Asia/Sakhalin" },
  { label: "Samarkand", value: "Asia/Samarkand" },
  { label: "Seoul", value: "Asia/Seoul" },
  { label: "Shanghai", value: "Asia/Shanghai" },
  { label: "Singapore", value: "Asia/Singapore" },
  { label: "Srednekolymsk", value: "Asia/Srednekolymsk" },
  { label: "Taipei", value: "Asia/Taipei" },
  { label: "Tashkent", value: "Asia/Tashkent" },
  { label: "Tbilisi", value: "Asia/Tbilisi" },
  { label: "Tehran", value: "Asia/Tehran" },
  { label: "Thimphu", value: "Asia/Thimphu" },
  { label: "Tokyo", value: "Asia/Tokyo" },
  { label: "Tomsk", value: "Asia/Tomsk" },
  { label: "Ulaanbaatar", value: "Asia/Ulaanbaatar" },
  { label: "Urumqi", value: "Asia/Urumqi" },
  { label: "Ust-Nera", value: "Asia/Ust-Nera" },
  { label: "Vientiane", value: "Asia/Vientiane" },
  { label: "Vladivostok", value: "Asia/Vladivostok" },
  { label: "Yakutsk", value: "Asia/Yakutsk" },
  { label: "Yangon", value: "Asia/Yangon" },
  { label: "Yekaterinburg", value: "Asia/Yekaterinburg" },
  { label: "Yerevan", value: "Asia/Yerevan" },
  { label: "Azores", value: "Atlantic/Azores" },
  { label: "Bermuda", value: "Atlantic/Bermuda" },
  { label: "Canary", value: "Atlantic/Canary" },
  { label: "Cape Verde", value: "Atlantic/Cape_Verde" },
  { label: "Faroe", value: "Atlantic/Faroe" },
  { label: "Madeira", value: "Atlantic/Madeira" },
  { label: "Reykjavik", value: "Atlantic/Reykjavik" },
  { label: "South Georgia", value: "Atlantic/South_Georgia" },
  { label: "St Helena", value: "Atlantic/St_Helena" },
  { label: "Stanley", value: "Atlantic/Stanley" },
  { label: "Adelaide", value: "Australia/Adelaide" },
  { label: "Brisbane", value: "Australia/Brisbane" },
  { label: "Broken Hill", value: "Australia/Broken_Hill" },
  { label: "Currie", value: "Australia/Currie" },
  { label: "Darwin", value: "Australia/Darwin" },
  { label: "Eucla", value: "Australia/Eucla" },
  { label: "Hobart", value: "Australia/Hobart" },
  { label: "Lindeman", value: "Australia/Lindeman" },
  { label: "Lord Howe", value: "Australia/Lord_Howe" },
  { label: "Melbourne", value: "Australia/Melbourne" },
  { label: "Perth", value: "Australia/Perth" },
  { label: "Sydney", value: "Australia/Sydney" },
  { label: "Amsterdam", value: "Europe/Amsterdam" },
  { label: "Andorra", value: "Europe/Andorra" },
  { label: "Astrakhan", value: "Europe/Astrakhan" },
  { label: "Athens", value: "Europe/Athens" },
  { label: "Belgrade", value: "Europe/Belgrade" },
  { label: "Berlin", value: "Europe/Berlin" },
  { label: "Bratislava", value: "Europe/Bratislava" },
  { label: "Brussels", value: "Europe/Brussels" },
  { label: "Bucharest", value: "Europe/Bucharest" },
  { label: "Budapest", value: "Europe/Budapest" },
  { label: "Busingen", value: "Europe/Busingen" },
  { label: "Chisinau", value: "Europe/Chisinau" },
  { label: "Copenhagen", value: "Europe/Copenhagen" },
  { label: "Dublin", value: "Europe/Dublin" },
  { label: "Gibraltar", value: "Europe/Gibraltar" },
  { label: "Guernsey", value: "Europe/Guernsey" },
  { label: "Helsinki", value: "Europe/Helsinki" },
  { label: "Isle of Man", value: "Europe/Isle_of_Man" },
  { label: "Istanbul", value: "Europe/Istanbul" },
  { label: "Jersey", value: "Europe/Jersey" },
  { label: "Kaliningrad", value: "Europe/Kaliningrad" },
  { label: "Kiev", value: "Europe/Kiev" },
  { label: "Kirov", value: "Europe/Kirov" },
  { label: "Lisbon", value: "Europe/Lisbon" },
  { label: "Ljubljana", value: "Europe/Ljubljana" },
  { label: "London", value: "Europe/London" },
  { label: "Luxembourg", value: "Europe/Luxembourg" },
  { label: "Madrid", value: "Europe/Madrid" },
  { label: "Malta", value: "Europe/Malta" },
  { label: "Mariehamn", value: "Europe/Mariehamn" },
  { label: "Minsk", value: "Europe/Minsk" },
  { label: "Monaco", value: "Europe/Monaco" },
  { label: "Moscow", value: "Europe/Moscow" },
  { label: "Oslo", value: "Europe/Oslo" },
  { label: "Paris", value: "Europe/Paris" },
  { label: "Podgorica", value: "Europe/Podgorica" },
  { label: "Prague", value: "Europe/Prague" },
  { label: "Riga", value: "Europe/Riga" },
  { label: "Rome", value: "Europe/Rome" },
  { label: "Samara", value: "Europe/Samara" },
  { label: "San Marino", value: "Europe/San_Marino" },
  { label: "Sarajevo", value: "Europe/Sarajevo" },
  { label: "Saratov", value: "Europe/Saratov" },
  { label: "Simferopol", value: "Europe/Simferopol" },
  { label: "Skopje", value: "Europe/Skopje" },
  { label: "Sofia", value: "Europe/Sofia" },
  { label: "Stockholm", value: "Europe/Stockholm" },
  { label: "Tallinn", value: "Europe/Tallinn" },
  { label: "Tirane", value: "Europe/Tirane" },
  { label: "Ulyanovsk", value: "Europe/Ulyanovsk" },
  { label: "Uzhgorod", value: "Europe/Uzhgorod" },
  { label: "Vaduz", value: "Europe/Vaduz" },
  { label: "Vatican", value: "Europe/Vatican" },
  { label: "Vienna", value: "Europe/Vienna" },
  { label: "Vilnius", value: "Europe/Vilnius" },
  { label: "Volgograd", value: "Europe/Volgograd" },
  { label: "Warsaw", value: "Europe/Warsaw" },
  { label: "Zagreb", value: "Europe/Zagreb" },
  { label: "Zaporozhye", value: "Europe/Zaporozhye" },
  { label: "Zurich", value: "Europe/Zurich" },
  { label: "Antananarivo", value: "Indian/Antananarivo" },
  { label: "Chagos", value: "Indian/Chagos" },
  { label: "Christmas", value: "Indian/Christmas" },
  { label: "Cocos", value: "Indian/Cocos" },
  { label: "Comoro", value: "Indian/Comoro" },
  { label: "Kerguelen", value: "Indian/Kerguelen" },
  { label: "Mahe", value: "Indian/Mahe" },
  { label: "Maldives", value: "Indian/Maldives" },
  { label: "Mauritius", value: "Indian/Mauritius" },
  { label: "Mayotte", value: "Indian/Mayotte" },
  { label: "Reunion", value: "Indian/Reunion" },
  { label: "Apia", value: "Pacific/Apia" },
  { label: "Auckland", value: "Pacific/Auckland" },
  { label: "Bougainville", value: "Pacific/Bougainville" },
  { label: "Chatham", value: "Pacific/Chatham" },
  { label: "Chuuk", value: "Pacific/Chuuk" },
  { label: "Easter", value: "Pacific/Easter" },
  { label: "Efate", value: "Pacific/Efate" },
  { label: "Enderbury", value: "Pacific/Enderbury" },
  { label: "Fakaofo", value: "Pacific/Fakaofo" },
  { label: "Fiji", value: "Pacific/Fiji" },
  { label: "Funafuti", value: "Pacific/Funafuti" },
  { label: "Galapagos", value: "Pacific/Galapagos" },
  { label: "Gambier", value: "Pacific/Gambier" },
  { label: "Guadalcanal", value: "Pacific/Guadalcanal" },
  { label: "Guam", value: "Pacific/Guam" },
  { label: "Honolulu", value: "Pacific/Honolulu" },
  { label: "Kiritimati", value: "Pacific/Kiritimati" },
  { label: "Kosrae", value: "Pacific/Kosrae" },
  { label: "Kwajalein", value: "Pacific/Kwajalein" },
  { label: "Majuro", value: "Pacific/Majuro" },
  { label: "Marquesas", value: "Pacific/Marquesas" },
  { label: "Midway", value: "Pacific/Midway" },
  { label: "Nauru", value: "Pacific/Nauru" },
  { label: "Niue", value: "Pacific/Niue" },
  { label: "Norfolk", value: "Pacific/Norfolk" },
  { label: "Noumea", value: "Pacific/Noumea" },
  { label: "Pago Pago", value: "Pacific/Pago_Pago" },
  { label: "Palau", value: "Pacific/Palau" },
  { label: "Pitcairn", value: "Pacific/Pitcairn" },
  { label: "Pohnpei", value: "Pacific/Pohnpei" },
  { label: "Port Moresby", value: "Pacific/Port_Moresby" },
  { label: "Rarotonga", value: "Pacific/Rarotonga" },
  { label: "Saipan", value: "Pacific/Saipan" },
  { label: "Tahiti", value: "Pacific/Tahiti" },
  { label: "Tarawa", value: "Pacific/Tarawa" },
  { label: "Tongatapu", value: "Pacific/Tongatapu" },
  { label: "Truk", value: "Pacific/Truk" },
  { label: "Wake", value: "Pacific/Wake" },
  { label: "Wallis", value: "Pacific/Wallis" },
  { label: "worldclock", value: "UTC" },
];
